"""add property search indexes

Revision ID: 53d53278b6b4
Revises: 983d12dd9075
Create Date: 2026-10-08 21:37:02.744092

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '53d53278b6b4'
down_revision: Union[str, Sequence[str], None] = '983d12dd9075'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_properties_bedrooms', 'properties', ['bedrooms'], unique=False)
    op.create_index('ix_properties_created_at', 'properties', ['created_at'], unique=False)
    op.create_index('ix_properties_furnishing_status', 'properties', ['furnishing_status'], unique=False)
    op.create_index('ix_properties_is_available', 'properties', ['is_available'], unique=False)
    op.create_index('ix_properties_monthly_rent', 'properties', ['monthly_rent'], unique=False)
    op.create_index('ix_properties_property_type', 'properties', ['property_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_properties_property_type', table_name='properties')
    op.drop_index('ix_properties_monthly_rent', table_name='properties')
    op.drop_index('ix_properties_is_available', table_name='properties')
    op.drop_index('ix_properties_furnishing_status', table_name='properties')
    op.drop_index('ix_properties_created_at', table_name='properties')
    op.drop_index('ix_properties_bedrooms', table_name='properties')
    # ### end Alembic commands ###